#ifndef RDA5807_H_INCLUDED
#define RDA5807_H_INCLUDED

#include <inttypes.h>

#define RDA5807_ADDRESS		0x11
#define RDA5807_CHIP_ID		0x5804

enum rda_reg_t
{
	RDA_REG_CHIP_ID = 0x00,
	RDA_REG_CTRL_02 = 0x02,
	RDA_REG_CTRL_03 = 0x03,
	RDA_REG_CTRL_04 = 0x04,
	RDA_REG_CTRL_05 = 0x05,
	RDA_REG_CTRL_06 = 0x06,
	RDA_REG_CTRL_07 = 0x07,
	RDA_REG_CTRL_08 = 0x08,
	RDA_REG_CTRL_0A = 0x0A,
	RDA_REG_CTRL_0B = 0x0B,
	RDA_REG_CTRL_0C = 0x0C,
	RDA_REG_CTRL_0D = 0x0D,
	RDA_REG_CTRL_0E = 0x0E,
	RDA_REG_CTRL_0F = 0x0F,
};

#define RDA_REG_CTRL_02_AUDIO_ENABLE			(1 << 0xF)
#define RDA_REG_CTRL_02_MUTE_DISABLE			(1 << 0xE)
#define RDA_REG_CTRL_02_MONO_ENABLE			(1 << 0xD)
#define RDA_REG_CTRL_02_BASS_BOOST			(1 << 0xC)
#define RDA_REG_CTRL_02_RCLK_SUPPLY			(1 << 0xB)
#define RDA_REG_CTRL_02_RCLK_DIRECT			(1 << 0xA)
#define RDA_REG_CTRL_02_SEEK_UP				(1 << 0x9)
#define RDA_REG_CTRL_02_SEEK_ENABLE			(1 << 0x8)
#define RDA_REG_CTRL_02_SEEK_WRAP_DISABLE		(1 << 0x7)
#define RDA_REG_CTRL_02_CLK_MODE_Pos			0x4
#define RDA_REG_CTRL_02_CLK_MODE_Msk			(7 << RDA_REG_CTRL_02_CLK_MODE_Pos)
#define RDA_REG_CTRL_02_CLK_MODE_32kHz			(0 << RDA_REG_CTRL_02_CLK_MODE_Pos)
#define RDA_REG_CTRL_02_CLK_MODE_12MHz			(1 << RDA_REG_CTRL_02_CLK_MODE_Pos)
#define RDA_REG_CTRL_02_CLK_MODE_24MHz			(5 << RDA_REG_CTRL_02_CLK_MODE_Pos)
#define RDA_REG_CTRL_02_CLK_MODE_13MHz			(2 << RDA_REG_CTRL_02_CLK_MODE_Pos)
#define RDA_REG_CTRL_02_CLK_MODE_26MHz			(6 << RDA_REG_CTRL_02_CLK_MODE_Pos)
#define RDA_REG_CTRL_02_CLK_MODE_19MHz			(3 << RDA_REG_CTRL_02_CLK_MODE_Pos)
#define RDA_REG_CTRL_02_CLK_MODE_38MHz			(7 << RDA_REG_CTRL_02_CLK_MODE_Pos)
#define RDA_REG_CTRL_02_RDS_ENABLE			(1 << 0x3)
#define RDA_REG_CTRL_02_IMPROVE_SENSITIVITY		(1 << 0x2)
#define RDA_REG_CTRL_02_SOFT_RESET			(1 << 0x1)
#define RDA_REG_CTRL_02_POWER_ENABLE			(1 << 0x0)

#define RDA_REG_CTRL_03_CHANNEL_Pos			0x6
#define RDA_REG_CTRL_03_CHANNEL_Msk			(1023 << RDA_REG_CTRL_03_CHANNEL_Pos)
#define RDA_REG_CTRL_03_DIRECT_MODE			(1 << 0x5)
#define RDA_REG_CTRL_03_TUNE_ENABLE			(1 << 0x4)
#define RDA_REG_CTRL_03_BAND_SELECT_Pos			0x2
#define RDA_REG_CTRL_03_BAND_SELECT_Msk			(3 << RDA_REG_CTRL_03_BAND_SELECT_Pos)
#define RDA_REG_CTRL_03_BAND_SELECT_EU_US		(0 << RDA_REG_CTRL_03_BAND_SELECT_Pos)
#define RDA_REG_CTRL_03_BAND_SELECT_JAPAN		(1 << RDA_REG_CTRL_03_BAND_SELECT_Pos)
#define RDA_REG_CTRL_03_BAND_SELECT_WW			(2 << RDA_REG_CTRL_03_BAND_SELECT_Pos)
#define RDA_REG_CTRL_03_BAND_SELECT_EAST_EU		(3 << RDA_REG_CTRL_03_BAND_SELECT_Pos)
#define RDA_REG_CTRL_03_CHANNEL_SPACING_Pos		0x0
#define RDA_REG_CTRL_03_CHANNEL_SPACING_Msk		(3 << RDA_REG_CTRL_03_CHANNEL_SPACING_Pos)
#define RDA_REG_CTRL_03_CHANNEL_SPACING_100kHz		(0 << RDA_REG_CTRL_03_CHANNEL_SPACING_Pos)
#define RDA_REG_CTRL_03_CHANNEL_SPACING_200kHz		(1 << RDA_REG_CTRL_03_CHANNEL_SPACING_Pos)
#define RDA_REG_CTRL_03_CHANNEL_SPACING_50kHz		(2 << RDA_REG_CTRL_03_CHANNEL_SPACING_Pos)
#define RDA_REG_CTRL_03_CHANNEL_SPACING_25kHz		(3 << RDA_REG_CTRL_03_CHANNEL_SPACING_Pos)

#define RDA_REG_CTRL_04_SEEK_TUNE_INTR_ENABLE		(1 << 0xE)
#define RDA_REG_CTRL_04_RDBS_ENABLE			(1 << 0xD)
#define RDA_REG_CTRL_04_RDS_FIFO_ENABLE			(1 << 0xC)
#define RDA_REG_CTRL_04_DE_EMPHASIS			(1 << 0xB)
#define RDA_REG_CTRL_04_RDS_FIFO_CLEAR			(1 << 0xA)
#define RDA_REG_CTRL_04_SOFTMUTE_ENABLE			(1 << 0x9)
#define RDA_REG_CTRL_04_AFC_DISABLE			(1 << 0x8)

#define RDA_REG_CTRL_05_INT_MODE			(1 << 0xF)
#define RDA_REG_CTRL_05_SEEK_MODE_Pos			0xE
#define RDA_REG_CTRL_05_SEEK_MODE_Msk			(3 << RDA_REG_CTRL_05_SEEK_MODE_Pos)
#define RDA_REG_CTRL_05_SEEK_SNR_Pos			0x8
#define RDA_REG_CTRL_05_SEEK_SNR_Msk			(15 << RDA_REG_CTRL_05_SEEK_SNR_Pos)
#define RDA_REG_CTRL_05_LNA_SELECT_Pos			0x6
#define RDA_REG_CTRL_05_LNA_SELECT_Msk			(3 << RDA_REG_CTRL_05_LNA_SELECT_Pos)
#define RDA_REG_CTRL_05_LNA_CURRENT_SELECT_Pos		0x4
#define RDA_REG_CTRL_05_LNA_CURRENT_SELECT_Msk		(3 << RDA_REG_CTRL_05_LNA_CURRENT_SELECT_Pos)
#define RDA_REG_CTRL_05_VOLUME_Pos			0x0
#define RDA_REG_CTRL_05_VOLUME_Msk			(15 << RDA_REG_CTRL_05_VOLUME_Pos)

// #define RDA_REG_CTRL_06 (I2S only?)

#define RDA_REG_CTRL_07_THESHHOLD_SOFT_BLEND_Pos	0xA
#define RDA_REG_CTRL_07_THESHHOLD_SOFT_BLEND_Msk	(63 << RDA_REG_CTRL_07_THESHHOLD_SOFT_BEND_Pos)
#define RDA_REG_CTRL_07_65M_50M_MODE			(1 << 0x9)
#define RDA_REG_CTRL_07_SOFT_BLEND_ENABLE		(1 << 0x1)
#define RDA_REG_CTRL_07_FREQ_MODE			(1 << 0x0)

#define RDA_REG_CTRL_08_FREQ_DIRECT_Pos			0x0
#define RDA_REG_CTRL_08_FREQ_DIRECT_Msk			(0xFFFF << RDA_REG_CTRL_08_FREQ_DIRECT_Pos)

#define RDA_REG_CTRL_0A_RDS_READY			(1 << 0xF)
#define RDA_REG_CTRL_0A_SEEK_TUNE_COMPLETE		(1 << 0xE)
#define RDA_REG_CTRL_0A_SEEK_TUNE_FAILURE		(1 << 0xD)
#define RDA_REG_CTRL_0A_RDS_SYNCHRONIZED		(1 << 0xC)
#define RDA_REG_CTRL_0A_BLOCK_E_FOUND			(1 << 0xB)
#define RDA_REG_CTRL_0A_STEREO_ENABLED			(1 << 0xA)
#define RDA_REG_CTRL_0A_READ_CHANNEL_Pos		0x0
#define RDA_REG_CTRL_0A_READ_CHANNEL_Msk		(1023 << RDA_REG_CTRL_0A_READ_CHANNEL_Pos)

#define RDA_REG_CTRL_0B_RSSI_Pos			0x9
#define RDA_REG_CTRL_0B_RSSI_Msk			(255 << RDA_REG_CTRL_0B_RSSI_Pos)
#define RDA_REG_CTRL_0B_FM_IS_STATION			(1 << 0x8)
#define RDA_REG_CTRL_0B_FM_READY			(1 << 0x7)
#define RDA_REG_CTRL_0B_BLOCK_IS_E			(1 << 0x4)
#define RDA_REG_CTRL_0B_BLOCK_ERROR_LEVEL_A_Pos		0x2
#define RDA_REG_CTRL_0B_BLOCK_ERROR_LEVEL_A_Msk		(3 << RDA_REG_CTRL_0B_BLOCK_ERROR_LEVEL_A_Pos)
#define RDA_REG_CTRL_0B_BLOCK_ERROR_LEVEL_B_Pos		0x0
#define RDA_REG_CTRL_0B_BLOCK_ERROR_LEVEL_B_Msk		(3 << RDA_REG_CTRL_0B_BLOCK_ERROR_LEVEL_B_Pos)

#define RDA_REG_CTRL_0C_RDS_BLOCK_A_Pos			0x0
#define RDA_REG_CTRL_0C_RDS_BLOCK_A_Msk			(0xFFFF << RDA_REG_CTRL_0C_RDS_BLOCK_A_Pos)

#define RDA_REG_CTRL_0D_RDS_BLOCK_B_Pos			0x0
#define RDA_REG_CTRL_0D_RDS_BLOCK_B_Msk			(0xFFFF << RDA_REG_CTRL_0D_RDS_BLOCK_B_Pos)

#define RDA_REG_CTRL_0E_RDS_BLOCK_C_Pos			0x0
#define RDA_REG_CTRL_0E_RDS_BLOCK_C_Msk			(0xFFFF << RDA_REG_CTRL_0E_RDS_BLOCK_C_Pos)

#define RDA_REG_CTRL_0F_RDS_BLOCK_D_Pos			0x0
#define RDA_REG_CTRL_0F_RDS_BLOCK_D_Msk			(0xFFFF << RDA_REG_CTRL_0F_RDS_BLOCK_D_Pos)


uint32_t rda_init(void);
uint32_t rda_set_frequency(uint32_t freq_khz);
uint32_t rda_seek(void);
uint32_t rda_set_volume(uint8_t volume);
uint32_t rda_read_status_register(uint16_t *reg);

#endif // RDA5807_H_INCLUDED
