#include "header.h"

void GPIOConfig(void)
{
	// enable GPIO clock
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOCEN;

	// reset PA0, PA1, PA2, PA3 mode
	GPIOA->MODER &= ~(GPIO_MODER_MODER0_Msk | GPIO_MODER_MODER1_Msk | GPIO_MODER_MODER2_Msk | GPIO_MODER_MODER3_Msk);
	// set PA0, PA1, PA2, PA3 to output mode (MODER1 = 0b01)
	GPIOA->MODER |= (GPIO_MODER_MODER0_0 | GPIO_MODER_MODER1_0 | GPIO_MODER_MODER2_0 | GPIO_MODER_MODER3_0);

	// set PC13 (dbg led)
	GPIOC->MODER &= ~GPIO_MODER_MODER13_Msk;
	GPIOC->MODER |= GPIO_MODER_MODER13_0;
	GPIOC->OTYPER &= ~GPIO_OTYPER_OT13;
}