#ifndef LCD_H_INCLUDED
#define LCD_H_INCLUDED

#include "header.h"


#define LCD_ENTRY_MODE_INC_DEC_ENABLE		0x01
#define LCD_ENTRY_MODE_INC_DEC_DISABLE		0x00
#define LCD_ENTRY_MODE_INCREMENT		0x02
#define LCD_ENTRY_MODE_DECREMENT		0x00

#define LCD_DISPLAY_ENABLE			0x04
#define LCD_DISPLAY_DISABLE			0x00
#define LCD_DISPLAY_CURSOR_ENABLE		0x02
#define LCD_DISPLAY_CURSOR_DISABLE		0x00
#define LCD_DISPLAY_CURSOR_BLINK		0x01
#define LCD_DISPLAY_CURSOR_STATC		0x00

#define LCD_CURSOR_DISPLAY_SHIFT_DISPLAY	0x08
#define LCD_CURSOR_DISPLAY_SHIFT_CURSOR		0x00
#define LCD_CURSOR_DISPLAY_SHIFT_RIGHT		0x04
#define LCD_CURSOR_DISPLAY_SHIFT_LEFT		0x00

#define LCD_FUNCTION_SET_DATA_LENGTH_8_BIT	0x10
#define LCD_FUNCTION_SET_DATA_LENGTH_4_BIT	0x00
#define LCD_FUNCTION_SET_2_LINES		0x08
#define LCD_FUNCTION_SET_1_LINE			0x00
#define LCD_FUNCTION_SET_FONT_5x10		0x04
#define LCD_FUNCTION_SET_FONT_5x8		0x00

#endif // LCD_H_INCLUDED
